# Generated by Django 6.0 on 2025-12-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='mavjud',
            field=models.CharField(choices=[('mavjud', 'Mavjud'), ('tugagan', 'Tugagan')], default='mavjud', max_length=20),
        ),
    ]
