# Generated by Django 6.0 on 2025-12-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_mavjud'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
