# Generated by Django 6.0 on 2025-12-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmaitems',
            name='buyurtma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtma', to='food.buyurtma'),
        ),
    ]
